### ISSUE TITLE
Serialize doesn't work

### ISSUE THREAD

**Issue by Secretmapper** [rse/asty#1]
Serialize doesn't seem to work for whatever reason - the member `serialize` is undefined.

```
  const ast = parser(str).ast
  // ast is an ASTYnode
  // i.e. ast.ASTy evaluates to true
  const exprs = ast.childs()[0].childs()[0]  // valid, returns the node I want
  console.log(ast.serialize)                       // undefined
```

p.s. the reason I want to use the serialize/unserialize family of functions is because I want to unit test that my file returns my expected parse tree (I'm using PEGutil). I'm thinking of using serialize/unserialize to do this.

I also tried creating my ast tree manually (through asty) but unfortunately `.deepEqual` won't work with them as my actual ast contains line information (presumably, the `[1/5]` etc. lines when the file is dumped).

p.p.s. would you recommend a way for me to unit test ast? I'm actually thinking of just comparing the dump with a string, seems to be the easiest way (writing out the dump is cleaner than writing out the JSON), but is bound to be brittle

**Comment by PC123PC** [comment]
Can you get in touch with me about the Salescamp project? Hoping to finish it up and I haven't heard from you in a month? Thanks!

**Comment by rse** [comment]
The serialize() API bug is now fixed. For unit testing your AST you either can serialize it and then compare it 1:1 or perhaps also look at my AST (https://github.com/rse/astq), which allows you to perform powerful queries on ASTy structures. The most easy way to use ASTy and ASTq together is with my ASTy-ASTq (https://github.com/rse/asty-astq).
